-- gestures.lua — JarvisHands: Custom Hand Gesture Modal for Hammerspoon
-- Loads gesture-to-action mappings from ~/.jarvishands/mappings.lua
-- (auto-generated by the JarvisHands web UI).

local M = {}

local gestureTask = nil
local active = false
local gestureCanvas = nil

local HOME = os.getenv("HOME")
local SCRIPT_PATH = HOME .. "/Projects/jarvishands/gesture_detector.py"
local PYTHON = "/usr/bin/python3"
local MAPPINGS_LUA = HOME .. "/.jarvishands/mappings.lua"

-- Count table keys
local function tableSize(t)
    local n = 0
    for _ in pairs(t) do n = n + 1 end
    return n
end

-- ─── Load Mappings ────────────────────────────────────────────────
-- Mappings are auto-generated by the web UI into a Lua file.
-- Each entry: { [gesture_name] = { name = "...", action = function() ... end } }
M.mappings = {}

local function loadMappings()
    local f = io.open(MAPPINGS_LUA, "r")
    if f then
        f:close()
        local ok, result = pcall(dofile, MAPPINGS_LUA)
        if ok and type(result) == "table" then
            M.mappings = result
            print("[gestures] Loaded " .. tableSize(result) .. " mappings")
        else
            print("[gestures] Failed to load mappings: " .. tostring(result))
        end
    end
end

-- ─── Status Indicator ─────────────────────────────────────────────
local function showIndicator(text, color)
    if gestureCanvas then gestureCanvas:delete() end

    gestureCanvas = hs.canvas.new({x = 20, y = 40, w = 280, h = 36})
    gestureCanvas:appendElements({
        {
            type = "rectangle",
            roundedRectRadii = {xRadius = 8, yRadius = 8},
            fillColor = {alpha = 0.85, red = color[1], green = color[2], blue = color[3]},
            strokeColor = {alpha = 0.4, white = 1},
            strokeWidth = 1,
        },
        {
            type = "text",
            text = text,
            textColor = {white = 1},
            textSize = 14,
            textAlignment = "center",
            frame = {x = 0, y = 8, w = 280, h = 24},
        },
    })
    gestureCanvas:level(hs.canvas.windowLevels.overlay)
    gestureCanvas:show()
end

local function hideIndicator()
    if gestureCanvas then
        gestureCanvas:delete()
        gestureCanvas = nil
    end
end

-- ─── Gesture Callback (called from Python via hs CLI) ─────────────
function gestureReceived(gesture)
    local mapping = M.mappings[gesture]
    if mapping then
        showIndicator("Gesture: " .. mapping.name, {0.1, 0.6, 0.3})
        hs.timer.doAfter(1.5, function()
            if active then
                showIndicator("JarvisHands Active", {0.2, 0.4, 0.8})
            end
        end)
        mapping.action()
    else
        showIndicator("Unmapped: " .. gesture, {0.7, 0.4, 0.1})
        hs.timer.doAfter(1.5, function()
            if active then
                showIndicator("JarvisHands Active", {0.2, 0.4, 0.8})
            end
        end)
        print("[gestures] Unmapped gesture: " .. gesture)
    end
end

-- ─── Start / Stop ─────────────────────────────────────────────────
function M.start()
    if active then return end

    -- Reload mappings every time we start
    loadMappings()

    active = true
    showIndicator("JarvisHands Active", {0.2, 0.4, 0.8})
    hs.alert.show("JarvisHands ON (" .. tableSize(M.mappings) .. " mappings)")

    gestureTask = hs.task.new(PYTHON, function(exitCode, stdOut, stdErr)
        print("[gestures] Python exited: " .. tostring(exitCode))
        if stdErr and #stdErr > 0 then print("[gestures] " .. stdErr) end
        active = false
        hideIndicator()
    end, function(task, stdOut, stdErr)
        if stdOut and #stdOut > 0 then print("[gestures] " .. stdOut) end
        if stdErr and #stdErr > 0 then print("[gestures] err: " .. stdErr) end
        return true
    end, {SCRIPT_PATH, "--run"})

    if gestureTask then
        gestureTask:start()
    else
        hs.alert.show("Failed to start JarvisHands")
        active = false
        hideIndicator()
    end
end

function M.stop()
    if not active then return end
    active = false

    if gestureTask then
        gestureTask:terminate()
        gestureTask = nil
    end

    hideIndicator()
    hs.alert.show("JarvisHands OFF")
end

function M.toggle()
    if active then
        M.stop()
    else
        M.start()
    end
end

function M.isActive()
    return active
end

-- ─── Hotkey Binding ───────────────────────────────────────────────
function M.bindHotkeys()
    -- Ctrl+Cmd+G toggles gesture detection
    hs.hotkey.bind({"ctrl", "cmd"}, "g", function()
        M.toggle()
    end)
end

-- Load mappings on init
loadMappings()

return M
