-- gestures.lua — JarvisHands: Custom Hand Gesture Modal for Hammerspoon
-- Loads gesture-to-action mappings from ~/.jarvishands/mappings.lua
-- (auto-generated by the JarvisHands web UI).

local M = {}

local gestureTask = nil
local active = false
local gestureCanvas = nil

local HOME = os.getenv("HOME")
local SCRIPT_PATH = HOME .. "/Projects/jarvishands/gesture_detector.py"
local PYTHON = "/usr/bin/python3"
local MAPPINGS_LUA = HOME .. "/.jarvishands/mappings.lua"

-- Count table keys
local function tableSize(t)
    local n = 0
    for _ in pairs(t) do n = n + 1 end
    return n
end

-- ─── Load Mappings ────────────────────────────────────────────────
-- Mappings are auto-generated by the web UI into a Lua file.
-- Each entry: { [gesture_name] = { name = "...", action = function() ... end } }
M.mappings = {}

local function loadMappings()
    local f = io.open(MAPPINGS_LUA, "r")
    if f then
        f:close()
        local ok, result = pcall(dofile, MAPPINGS_LUA)
        if ok and type(result) == "table" then
            M.mappings = result
            print("[gestures] Loaded " .. tableSize(result) .. " mappings")
        else
            print("[gestures] Failed to load mappings: " .. tostring(result))
        end
    end
end

-- ─── Status Indicator ─────────────────────────────────────────────
local function showIndicator(text, color)
    if gestureCanvas then gestureCanvas:delete() end

    gestureCanvas = hs.canvas.new({x = 20, y = 40, w = 280, h = 36})
    gestureCanvas:appendElements({
        {
            type = "rectangle",
            roundedRectRadii = {xRadius = 8, yRadius = 8},
            fillColor = {alpha = 0.85, red = color[1], green = color[2], blue = color[3]},
            strokeColor = {alpha = 0.4, white = 1},
            strokeWidth = 1,
        },
        {
            type = "text",
            text = text,
            textColor = {white = 1},
            textSize = 14,
            textAlignment = "center",
            frame = {x = 0, y = 8, w = 280, h = 24},
        },
    })
    gestureCanvas:level(hs.canvas.windowLevels.overlay)
    gestureCanvas:show()
end

local function hideIndicator()
    if gestureCanvas then
        gestureCanvas:delete()
        gestureCanvas = nil
    end
end

-- ─── Gesture Callback (called from Python via hs CLI) ─────────────
function gestureReceived(gesture)
    local mapping = M.mappings[gesture]
    if mapping then
        showIndicator("Gesture: " .. mapping.name, {0.1, 0.6, 0.3})
        hs.timer.doAfter(1.5, function()
            if active then
                showIndicator("JarvisHands Active", {0.2, 0.4, 0.8})
            else
                hideIndicator()
            end
        end)
        mapping.action()
    else
        showIndicator("Unmapped: " .. gesture, {0.7, 0.4, 0.1})
        hs.timer.doAfter(1.5, function()
            if active then
                showIndicator("JarvisHands Active", {0.2, 0.4, 0.8})
            else
                hideIndicator()
            end
        end)
        print("[gestures] Unmapped gesture: " .. gesture)
    end
end

-- ─── Aim Mode (called from Python via hs CLI) ───────────────────────
local aimCanvas = nil
local aimActive = false

function jarvisAimEnter()
    aimActive = true
    showIndicator("AIM MODE", {0.0, 0.8, 0.9})
    print("[gestures] Aim mode entered")
end

function jarvisAimUpdate(x, y)
    if not aimActive then return end
    -- x,y are 0-1 normalized from camera (mirrored). Convert to screen coords.
    local screen = hs.screen.mainScreen():frame()
    -- Camera x is mirrored, so 0=right, 1=left in camera view
    local sx = screen.x + x * screen.w
    local sy = screen.y + y * screen.h

    -- Move the actual mouse cursor so it selects windows naturally
    hs.mouse.absolutePosition({x = sx, y = sy})

    -- Draw crosshair overlay
    if aimCanvas then aimCanvas:delete() end
    local size = 40
    aimCanvas = hs.canvas.new({x = sx - size/2, y = sy - size/2, w = size, h = size})
    aimCanvas:appendElements(
        {type = "circle", center = {x = size/2, y = size/2}, radius = size/2 - 2,
         strokeColor = {red = 0, green = 1, blue = 1, alpha = 0.8}, strokeWidth = 2,
         fillColor = {alpha = 0}},
        {type = "segments", coordinates = {{x = size/2, y = 2}, {x = size/2, y = size - 2}},
         strokeColor = {red = 0, green = 1, blue = 1, alpha = 0.8}, strokeWidth = 1.5},
        {type = "segments", coordinates = {{x = 2, y = size/2}, {x = size - 2, y = size/2}},
         strokeColor = {red = 0, green = 1, blue = 1, alpha = 0.8}, strokeWidth = 1.5},
        {type = "circle", center = {x = size/2, y = size/2}, radius = 3,
         fillColor = {red = 0, green = 1, blue = 1, alpha = 0.9}}
    )
    aimCanvas:level(hs.canvas.windowLevels.overlay + 1)
    aimCanvas:show()
end

function jarvisAimFire(x, y)
    if not aimActive then return end
    aimActive = false

    local screen = hs.screen.mainScreen():frame()
    local sx = screen.x + x * screen.w
    local sy = screen.y + y * screen.h

    -- Move mouse to target position
    hs.mouse.absolutePosition({x = sx, y = sy})

    -- Click to select/focus the window under cursor
    hs.eventtap.leftClick({x = sx, y = sy})

    -- Brief delay then quit the focused app
    hs.timer.doAfter(0.15, function()
        local win = hs.window.focusedWindow()
        if win then
            local app = win:application()
            local appName = app and app:name() or "unknown"
            showIndicator("QUIT: " .. appName, {0.9, 0.2, 0.2})
            -- Close the window (Cmd+W). Use app:kill() for full quit.
            win:close()
            print("[gestures] Closed window: " .. appName)
        end
    end)

    -- Clean up crosshair
    if aimCanvas then aimCanvas:delete(); aimCanvas = nil end

    hs.timer.doAfter(1.5, function()
        hideIndicator()
    end)
end

function jarvisAimExit()
    aimActive = false
    if aimCanvas then aimCanvas:delete(); aimCanvas = nil end
    hideIndicator()
    print("[gestures] Aim mode exited")
end

-- ─── Start / Stop ─────────────────────────────────────────────────
function M.start()
    if active then return end

    -- Reload mappings every time we start
    loadMappings()

    active = true
    showIndicator("JarvisHands Active", {0.2, 0.4, 0.8})
    hs.alert.show("JarvisHands ON (" .. tableSize(M.mappings) .. " mappings)")

    gestureTask = hs.task.new(PYTHON, function(exitCode, stdOut, stdErr)
        print("[gestures] Python exited: " .. tostring(exitCode))
        if stdErr and #stdErr > 0 then print("[gestures] " .. stdErr) end
        active = false
        hideIndicator()
    end, function(task, stdOut, stdErr)
        if stdOut and #stdOut > 0 then print("[gestures] " .. stdOut) end
        if stdErr and #stdErr > 0 then print("[gestures] err: " .. stdErr) end
        return true
    end, {SCRIPT_PATH, "--run"})

    if gestureTask then
        gestureTask:start()
    else
        hs.alert.show("Failed to start JarvisHands")
        active = false
        hideIndicator()
    end
end

function M.stop()
    if not active then return end
    active = false

    if gestureTask then
        gestureTask:terminate()
        gestureTask = nil
    end

    hideIndicator()
    hs.alert.show("JarvisHands OFF")
end

function M.toggle()
    if active then
        M.stop()
    else
        M.start()
    end
end

function M.isActive()
    return active
end

-- ─── Hotkey Binding ───────────────────────────────────────────────
function M.bindHotkeys()
    -- Ctrl+Cmd+G toggles gesture detection
    hs.hotkey.bind({"ctrl", "cmd"}, "g", function()
        M.toggle()
    end)
end

-- Load mappings on init
loadMappings()

return M
